version: '3.1'

services:
  app:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./uploads:/root/uploads

  db:
    image: mysql:5.7
    platform: linux/amd64
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: yujian
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
